### ISSUE TITLE
Wrong Connection Status

### ISSUE THREAD

**Issue by AlleSchonWeg** [geocom/Wahoo-Sender#6]
Hi,
as i mentioned earlier, that my device (Honor 9 / Android 9) changes the status from connected to disconnected, if device goes to background. Here is a logcat: 
> 2020-04-13 19:40:22.277 21478-21494/com.geocomnz.wahoosender V/BluetoothLeService: onReliableWriteCompleted
> 2020-04-13 19:40:27.270 21478-21537/com.geocomnz.wahoosender I/BluetoothLeService: characteristic android.bluetooth.BluetoothGattCharacteristic@5b22611
> 2020-04-13 19:40:27.270 21478-21537/com.geocomnz.wahoosender I/BluetoothLeService: data %00
> 2020-04-13 19:40:27.276 21478-21494/com.geocomnz.wahoosender V/BluetoothLeService: onReliableWriteCompleted
> 2020-04-13 19:40:29.808 21478-21478/com.geocomnz.wahoosender D/BluetoothLeService: Trying to use an existing mBluetoothGatt for connection.
> 2020-04-13 19:40:29.811 21478-21478/com.geocomnz.wahoosender D/DeviceControlActivity: Connect request result=true
> 2020-04-13 19:40:29.814 21478-21494/com.geocomnz.wahoosender D/BluetoothGatt: onClientConnectionState() - status=6 clientIf=7 device=4F:B4:20:66:F4:4B
> 2020-04-13 19:40:29.814 21478-21494/com.geocomnz.wahoosender I/BluetoothLeService: Disconnected from GATT server.
> 2020-04-13 19:40:29.856 21478-21511/com.geocomnz.wahoosender D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
> 2020-04-13 19:40:32.269 21478-21537/com.geocomnz.wahoosender I/BluetoothLeService: characteristic android.bluetooth.BluetoothGattCharacteristic@5b22611
> 2020-04-13 19:40:32.270 21478-21537/com.geocomnz.wahoosender I/BluetoothLeService: data %00

I also tried it with my old Galaxy S2 and this works as expected. No connection status changes.

**Comment by geocom** [comment]
Sorry its been awhile. Had a bunch of other coding to do. 

Looks like in the Huawei EMUI OS they have a thing called PowerGenie
https://dontkillmyapp.com/huawei

It kills anything not in their whitelist which of cause we wont be and I have long heard reports from Huawei owners that they have issues with power management. 

It does sound like something i cannot fix as it is not a issue with the app but with Huawei's os and PowerGenie needs to be un-installed by the user

**Comment by AlleSchonWeg** [comment]
Hi,
i use a custom ROM and tried to find the the com.huawei.powergenie process. But i have no such process. 
Thanks

**Comment by geocom** [comment]
Which custom ROM? Looking at the log above the likely option is we are getting shut down by battery saving of some sort.

There is a background timer that runs, if it stops running the wahoo will reset it's mac address. 
Does the mac address stay the same after having the app in the background for like 30-60 seconds?

**Comment by AlleSchonWeg** [comment]
An OpenKirin ROM: https://openkirin.net/download/ (OmniROM Beta 5)

If i have the sender app in background the elemnt bluetooth mac address stays the same. I assume you mean the address which the sender app shows. The elemnt still shows the phone icon in the settings. Only if i close the sender app and reconnect the elemnt mac address changes.
